version: "3"
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - laravel
      - mailhog
    working_dir: /var/www
    volumes:
      - ./docker/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./docker/nginx/ssl/server.key:/etc/nginx/ssl/server.key
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www:cached
    restart: always

  laravel:
    build: ./docker/laravel
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www:cached
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql:cached

  node:
    image: node:16
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www:cached

  mailhog:
    image: mailhog/mailhog
    environment:
      MH_UI_WEB_PATH: mailhog

  adminer:
    image: adminer
